/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class push_pushinterface */

#ifndef _Included_push_pushinterface
#define _Included_push_pushinterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     push_pushinterface
 * Method:    cpushinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_push_pushinterface_cpushinit
  (JNIEnv *, jclass);

/*
 * Class:     push_pushinterface
 * Method:    cpushuninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_push_pushinterface_cpushuninit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
